# Implementasi K-NN Algorithm (Tugas 3)

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore', category=UserWarning, append=True)

In [2]:
url = "https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv"
df = pd.read_csv(url)
df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [3]:
x = df.iloc[:, :-1]
y = df.loc[:, "variety"]
y = df['variety'].values

In [4]:
# splitting the data into training and test sets (80:20)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [5]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [6]:
x_new = [[5.8,	4.0,	1.2,	0.2]]
y_predict = knn.predict(x_new)

print(y_predict[0])

Setosa

In [7]:
import numpy as np
def knn1(arr, x, wisata, k=1):
  knn = []
  for i in arr:
    dist = np.array([np.linalg.norm(x[j] - i) for j in range(len(x))])
    idx_k3n = np.where(dist <= dist[np.argsort(dist)])
    k3n = []
    for j in idx_k3n[0]:
      if len(k3n) < k:
        k3n.append(wisata[j])
    knn.append(k3n)
  return knn

In [8]:
x = knn1(np.array(x_new),np.array(x_train), np.array(y_train))
x

[['Setosa']]